### ISSUE TITLE
Live tracker GPH doesnt function

### ISSUE THREAD

**Issue by axelsnoski** [Juijang/LootAppraiser#3]
Code should be changed in UI to:
```
-- calculate looted item value / hour
function private.CalcLootedItemValuePerHour(key)
    local offset = LA.Session.GetPauseStart() or time()
    local delta = offset - LA.Session.GetCurrentSession("start") - LA.Session.GetSessionPause()

    local factor = 3600
    local totalItemValue = LA.Session.GetCurrentSession(key) or 0
    local livGoldPerHour
    if totalItemValue == 0 then
        livGoldPerHour = 0
    else
        local livPerHour = ((totalItemValue/delta)*factor)
        livGoldPerHour = floor(livPerHour/10000)
    end

    return tostring(livGoldPerHour)
end
```

**Comment by Juijang** [comment]
no thats not the way the gph should be calculated for session durations below 60 minutes.

with your change a 10k drop after 5 seconds in the session will result in a gph value of 7200000 which makes no sense.

**Comment by axelsnoski** [comment]
well I recoded mine like that since its a "true" live view it will average out as you go, sure it will be high at first but after a few min of farming say herbs it should be correct if you are getting a fairly even amount incoming, I would suggest adding the option to do a true live view or track by the hour as you have it.

**Comment by Juijang** [comment]
true, stuff like herbs need a different calculation. you did not have the wide range of gold value per item. on the other hand is transmog which is the primary goal of loot appraiser. the gold value varies in a wide range and calculating a gph with your formular makes really no sense.
currently it is not planned to have mutliple formulars depending on the type of the items and we stick with the 'transmog' friendly formular.

**Comment by axelsnoski** [comment]
Sure I get that, though if you think about it your formula is still a little skewed since you still calculate the average by the hour so rare item that you will not see drop again that dropped at 5 sec should never be averaged out. The calculation should be (NoteworthyItemsValue + ((NonNoteworthtemValue/delta)*factor)) then you use the noteworthy value to segment out the rare drops since you may only see one of those in a year in some cases.

**Comment by Juijang** [comment]
no changes planned. sorry

**Comment by axelsnoski** [comment]
no worries, you keep doing you :) I'll keep my improvements to myself :P
